name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y   
          sudo apt install libncurses5-dev python2 libtinfo5 -y      
          bash init_clang_12.sh
          
      - name: Set environment variable
        run: |
          echo "SEXY_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building sExy
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -c

      - name: Building sExy + KernelSU
        run: |
          export PATH=$HOME/:$PWD/toolchain/bin:$PATH
          bash build_kernel.sh -k          

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "sExy-${{ env.SEXY_KERNEL_VERSION }}-[Note 10]"
          path: |
            out/sExy*.xz
            out/KSU*.xz

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "sExy Kernel ${{ env.SEXY_KERNEL_VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}          
          artifacts: "out/sExy*.xz,out/KSU*.xz"
          body: "Commit SHA: ${{ github.sha }}"